services:
  api:
    container_name: node_course_porto_api
    command: tcp db:5432 -t 30s -i 250ms
    build: .
    volumes:
      - ./:/usr/src:delegated
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
  db:
    container_name: node_course_porto_api_db
    image: postgres
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=node_course_porto
      - PGUSER=postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'db_prod']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
